- link:
    ~/.config/awesome/rc.lua: awesome/rc.lua
    ~/.config/awesome/theme.lua: awesome/theme.lua
    ~/.config/awesome/rules.lua: awesome/rules.lua
    ~/.config/awesome/json.lua: awesome/json.lua
    ~/.config/awesome/appmenu.lua: awesome/appmenu.lua 
    ~/.config/awesome/dummy.lua: awesome/dummy.lua
    ~/.config/awesome/titlebar.lua: awesome/titlebar.lua
    ~/.config/awesome/utils.lua: awesome/utils.lua
    ~/.config/awesome/DataDumper.lua: awesome/DataDumper.lua
    ~/.config/awesome/popup.lua: awesome/popup.lua
    ~/.config/awesome/freedesktop: awesome/freedesktop
    ~/.config/awesome/awesome-buttons: awesome/awesome-buttons
    ~/.config/awesome/awesome-wm-widgets: awesome/awesome-wm-widgets
    ~/.config/awesome/modalawesome: awesome/modalawesome
    ~/.config/awesome/smart_borders: awesome/smart_borders
    ~/.config/awesome/awesome-switcher: awesome/awesome-switcher
    ~/.config/awesome/lain: awesome/lain

