- link:
    ~/.config/awesome/rc.lua: awesome/rc.lua
    ~/.config/awesome/xrandr.lua: awesome/xrandr.lua
    ~/.config/awesome/theme.lua: awesome/theme.lua
    ~/.config/awesome/rules.lua: awesome/rules.lua
    ~/.config/awesome/json.lua: awesome/json.lua
    ~/.config/awesome/appmenu.lua: awesome/appmenu.lua 
    ~/.config/awesome/dummy.lua: awesome/dummy.lua
    ~/.config/awesome/titlebar.lua: awesome/titlebar.lua
    ~/.config/awesome/utils.lua: awesome/utils.lua
    ~/.config/awesome/DataDumper.lua: awesome/DataDumper.lua
    ~/.config/awesome/widgets.lua: awesome/widgets.lua
    ~/.config/awesome/popup.lua: awesome/popup.lua
    ~/.config/awesome/errors.lua: awesome/errors.lua
    ~/.config/awesome/menu.lua: awesome/menu.lua
    ~/.config/awesome/settings.lua: awesome/settings.lua
    ~/.config/awesome/hardware_compat.lua: awesome/hardware_compat.lua
    ~/.config/awesome/freedesktop: awesome/freedesktop
    ~/.config/awesome/bling: awesome/bling
    ~/.config/awesome/awesome-buttons: awesome/awesome-buttons
    ~/.config/awesome/awesome-wm-widgets: awesome/awesome-wm-widgets
    ~/.config/awesome/modalawesome: awesome/modalawesome
    ~/.config/awesome/smart_borders: awesome/smart_borders
    ~/.config/awesome/awesome-switcher: awesome/awesome-switcher
    ~/.config/awesome/foggy: awesome/foggy
    ~/.config/awesome/lain: awesome/lain
    ~/.config/awesome/amh: awesome/amh
    ~/.config/awesome/omegavoid: awesome/omegavoid
    ~/.config/awesome/collision: awesome/collision
    ~/.config/awesome/layout-machi: awesome/layout-machi

