- shell:
  -
    description: Clone fzf repo
    command: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf || echo "already installed"
  - 
    description: Update fzf
    command: pushd ~/.fzf && git pull && ./install && popd