- link:
    ~/.config/nvim/init.vim: neovim/init.vim
    ~/.config/nvim/plugins.vim: neovim/plugins.vim
    ~/.config/nvim/vscode.vim: neovim/vscode.vim
    ~/.config/nvim/keymap.vim: neovim/keymap.vim

    ~/.config/nvim/autoload/utils.vim: neovim/autoload/utils.vim
- shell:
    - 
      description: Install Neovim
      command: | 
          if   [ -x "$(command -v apk)"    ]; then sudo apk add --no-cache neovim
          elif [ -x "$(command -v apt-get)"]; then sudo apt-get install -y neovim
          elif [ -x "$(command -v pacman)" ]; then sudo pacman -S --noconfirm neovim
          else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: neovim">&2; fi