- link:
    ~/.zshrc:
        force: true
        path: zsh/zshrc
    ~/.dircolors: zsh/dircolors
    ~/.zshenv: zsh/zshenv
    ~/.zsh_aliases: zsh/zsh_aliases
- shell:
    -
      command: sh ~/.dotfiles/scripts/zsh_install.sh
      description: Installing Zsh
