- link:
    ~/.zshrc:
        force: true
        path: zsh/rc.zsh
    ~/.dircolors: zsh/dircolors.zsh
    ~/.zprofile: zsh/profile.zsh
    ~/.zshenv: zsh/env.zsh
    ~/.zsh_aliases: zsh/aliases.zsh
    ~/.zsh_plugins: zsh/plugins.zsh
    ~/.zshbookmarks: zsh/bookmarks.zsh
#- shell:
#    -
#      command: |
#        if   [ -x "$(command -v apk)"    ]; then sudo apk add --no-cache zsh
#        elif [ -x "$(command -v apt-get)"]; then sudo apt-get install -y zsh
#        elif [ -x "$(command -v pacman)" ]; then sudo pacman -S --noconfirm zsh
#        else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: zsh">&2; fi
#      description: Installing Zsh
