- defaults:
    link:
      relink: true
      create: true
      force: true
    shell:
      stdout: true
      stderr: true
- create:
    - ~/.config
- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true
- shell:
    -
        command: git submodule update --init --recursive
        description: Installing submodules
