local appmenu = {}

appmenu.Accessories = {
    { 'Application Finder', 'xfce4-appfinder', '/usr/share/icons/hicolor/128x128/apps/org.xfce.appfinder.png' },
    { 'Archive Manager', 'file-roller', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.ArchiveManager.png' },
    { 'Barrier', 'barrier', '/usr/share/icons/hicolor/scalable/apps/barrier.svg' },
    { 'Bitwarden', 'bitwarden-desktop', '/usr/share/icons/hicolor/128x128/apps/bitwarden.png' },
    { 'Characters', '/usr/bin/gnome-characters', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.Characters.png' },
    { 'Disks', 'gnome-disks', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.DiskUtility.png' },
    { 'Electorrent', 'electorrent', '/usr/share/pixmaps/electorrent.png' },
    { 'File Manager PCManFM', 'pcmanfm', '/usr/share/icons/Ambiant-MATE/apps/16/system-file-manager.svg' },
    { 'Files', 'nautilus --new-window', '/usr/share/icons/Ambiant-MATE/apps/16/org.gnome.Nautilus.svg' },
    { 'Fonts', 'gnome-font-viewer', '/usr/share/icons/Yaru-MATE-dark/16x16/categories/org.gnome.font-viewer.png' },
    { 'HydraPaper', '/usr/bin/hydrapaper', '/usr/share/icons/hicolor/scalable/apps/org.gabmus.hydrapaper.svg' },
    { 'Image Viewer', 'gpicview', '/usr/share/icons/hicolor/48x48/apps/gpicview.png' },
    { 'Klipper', 'klipper', '/usr/share/icons/breeze/apps/48/klipper.svg' },
    { 'Kvantum Manager', 'kvantummanager', '/usr/share/icons/hicolor/scalable/apps/kvantum.svg' },
    { 'Mousepad', 'mousepad', '/usr/share/icons/hicolor/128x128/apps/org.xfce.mousepad.png' },
    { 'Neovim', 'wezterm -e nvim', '/usr/share/pixmaps/nvim.png' },
    { 'Neovim-Qt', 'nvim-qt --', '/usr/share/icons/hicolor/192x192/apps/nvim-qt.png' },
    { 'Nextcloud Desktop', 'nextcloud --quit', '/usr/share/icons/hicolor/128x128/apps/Nextcloud.png' },
    { 'NoiseTorch', 'noisetorch', '/usr/share/icons/hicolor/256x256/apps/noisetorch.png' },
    { 'Passwords and Keys', 'seahorse', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.seahorse.Application.png' },
    { 'Screenkey', 'screenkey', '/usr/share/icons/Yaru-MATE-dark/16x16/categories/preferences-desktop-keyboard-shortcuts.png' },
    { 'Screenshot', 'gnome-screenshot --interactive', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.Screenshot.png' },
    { 'Screenshot', 'xfce4-screenshooter', '/usr/share/icons/hicolor/128x128/apps/org.xfce.screenshooter.png' },
    { 'Sensor Viewer', 'xfce4-sensors', '/usr/share/icons/hicolor/24x24/apps/xfce-sensors.png' },
    { 'Snake', '/home/omegarogue/snake-razer/bin/snake', '/home/omegarogue/.local/share/pixmaps/snake-razer.png' },
    { 'SpaceFM', 'spacefm', '/usr/share/icons/hicolor/48x48/apps/spacefm.png' },
    { 'SpaceFM File Search', 'spacefm --find-files', '/usr/share/icons/hicolor/48x48/apps/spacefm-find.png' },
    { 'Task Manager', 'xfce4-taskmanager', '/usr/share/icons/hicolor/128x128/apps/org.xfce.taskmanager.png' },
    { 'Uno Calculator', 'uno-calculator', '/usr/share/icons/hicolor/128x128/apps/uno-calculator.png' },
    { 'Vim', 'wezterm -e vim', '/usr/share/icons/hicolor/48x48/apps/gvim.png' },
    { 'Wacom Settings', 'wacom-settings', '/usr/share/icons/hicolor/scalable/apps/com.github.avargas05.wacom-settings.svg' },
    { 'WezTerm', 'wezterm', '/usr/share/icons/hicolor/128x128/apps/org.wezfurlong.wezterm.png' },
    { 'Xfburn', 'xfburn -i', '/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn.png' },
    { 'YubiKey Personalization Tool', 'yubikey-personalization-gui', '/usr/share/icons/hicolor/128x128/apps/yubikey-personalization-gui.png' },
    { 'Yubico Authenticator', 'yubioath-desktop', '/usr/share/pixmaps/com.yubico.yubioath.svg' },
    { 'picom', 'picom' },
}

appmenu.Development = {
    { 'Android Studio', '"/home/omegarogue/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546/bin/studio.sh"', '/home/omegarogue/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/.icon.svg' },
    { 'Arduino IDE', '"/home/omegarogue/Downloads/arduino-1.8.19-linux64/arduino-1.8.19/arduino"', '/home/omegarogue/.local/share/icons/hicolor/16x16/apps/arduino-arduinoide.png' },
    { 'CLion', '"/home/omegarogue/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/221.5080.224/bin/clion.sh"', '/home/omegarogue/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/.icon.svg' },
    { 'CMake', 'cmake-gui', '/usr/share/icons/hicolor/128x128/apps/CMakeSetup.png' },
    { 'D-Feet', 'd-feet', '/usr/share/icons/hicolor/scalable/apps/org.gnome.dfeet.svg' },
    { 'Electron', 'electron', '/usr/share/pixmaps/electron.png' },
    { 'Electron 16', 'electron16', '/usr/share/pixmaps/electron16.png' },
    { 'Electron 17', 'electron17', '/usr/share/pixmaps/electron17.png' },
    { 'FLUID', 'fluid', '/usr/share/icons/hicolor/128x128/apps/fluid.png' },
    { 'GoLand', '"/home/omegarogue/.local/share/JetBrains/Toolbox/apps/Goland/ch-0/221.5080.224/bin/goland.sh"', '/home/omegarogue/.local/share/JetBrains/Toolbox/apps/Goland/ch-0/.icon.svg' },
    { 'JetBrains Toolbox', '/home/omegarogue/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox', '/home/omegarogue/.local/share/JetBrains/Toolbox/toolbox.svg' },
    { 'PyCharm Professional', '"/home/omegarogue/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.5080.212/bin/pycharm.sh"', '/home/omegarogue/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/.icon.svg' },
    { 'Qt Assistant', 'assistant', '/usr/share/icons/hicolor/128x128/apps/assistant.png' },
    { 'Qt Designer', 'designer', '/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png' },
    { 'Qt Linguist', 'linguist', '/usr/share/icons/hicolor/128x128/apps/linguist.png' },
    { 'Qt QDBusViewer', 'qdbusviewer', '/usr/share/icons/hicolor/128x128/apps/qdbusviewer.png' },
    { 'Qt4 Assistant', 'assistant-qt4', '/usr/share/icons/hicolor/128x128/apps/assistant-qt4.png' },
    { 'Qt4 Designer', 'designer-qt4', '/usr/share/icons/hicolor/128x128/apps/designer-qt4.png' },
    { 'Qt4 Linguist', 'linguist-qt4', '/usr/share/icons/hicolor/128x128/apps/linguist-qt4.png' },
    { 'Qt4 QDbusViewer', 'qdbusviewer-qt4', '/usr/share/icons/hicolor/128x128/apps/qdbusviewer-qt4.png' },
    { 'Rider', '"/home/omegarogue/.local/share/JetBrains/Toolbox/apps/Rider/ch-0/221.5591.20/bin/rider.sh"', '/home/omegarogue/.local/share/JetBrains/Toolbox/apps/Rider/ch-0/.icon.svg' },
    { 'Segger JFlashExe', '/usr/bin/JFlashExe', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JFlashLiteExe', '/usr/bin/JFlashLiteExe', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JFlashSPI_CL', '/usr/bin/JFlashSPI_CL', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkConfigExe', '/usr/bin/JLinkConfigExe', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkExe', '/usr/bin/JLinkExe', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkGDBServer', '/usr/bin/JLinkGDBServer', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkGUIServerExe', '/usr/bin/JLinkGUIServerExe', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkLicenseManager', '/usr/bin/JLinkLicenseManager', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkRTTClient', '/usr/bin/JLinkRTTClient', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkRTTLogger', '/usr/bin/JLinkRTTLogger', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkRTTViewer', '/usr/bin/JLinkRTTViewerExe', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkRegistration', '/usr/bin/JLinkRegistration', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkRemoteServer', '/usr/bin/JLinkRemoteServer', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkSTM32', '/usr/bin/JLinkSTM32', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JLinkSWOViewer', '/usr/bin/JLinkSWOViewer', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JMemExe', '/usr/bin/JMemExe', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JRunExe', '/usr/bin/JRunExe', '/usr/share/pixmaps/JLink.svg' },
    { 'Segger JTAGLoadExe', '/usr/bin/JTAGLoadExe', '/usr/share/pixmaps/JLink.svg' },
    { 'UserFeedback Console', 'UserFeedbackConsole', '/usr/share/icons/Yaru-MATE-dark/16x16/legacy/search.svg' },
    { 'Visual Studio Code', '/usr/bin/code --unity-launch', '/usr/share/icons/visual-studio-code.png' },
    { 'WebStorm', '"/home/omegarogue/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/221.5080.193/bin/webstorm.sh"', '/home/omegarogue/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/.icon.svg' },
    { 'distcc monitor', 'distccmon-gnome', '/usr/share/pixmaps/distccmon-gnome.png' },
    { 'nRF Connect', 'nrfconnect', '/usr/share/icons/hicolor/128x128/apps/nrfconnect.png' },
    { 'stlink', 'stlink-gui', '/usr/share/icons/hicolor/scalable/apps/stlink-gui.svg' },
}

appmenu.Education = {
    { 'FreeCAD', 'FreeCAD', '/usr/share/icons/hicolor/scalable/apps/org.freecadweb.FreeCAD.svg' },
    { 'GeoGebra', 'geogebra', '/usr/share/icons/hicolor/scalable/apps/geogebra.svg' },
    { 'LibreOffice Math', 'libreoffice --math', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-math.png' },
}

appmenu.Science = {
    { 'FreeCAD', 'FreeCAD', '/usr/share/icons/hicolor/scalable/apps/org.freecadweb.FreeCAD.svg' },
    { 'GeoGebra', 'geogebra', '/usr/share/icons/hicolor/scalable/apps/geogebra.svg' },
    { 'KiCad', 'kicad', '/usr/share/icons/hicolor/128x128/apps/kicad.png' },
    { 'KiCad Gerber Viewer', 'gerbview', '/usr/share/icons/hicolor/128x128/apps/gerbview.png' },
    { 'KiCad Image Converter', 'bitmap2component', '/usr/share/icons/hicolor/128x128/apps/bitmap2component.png' },
    { 'KiCad PCB Calculator', 'pcb_calculator', '/usr/share/icons/hicolor/128x128/apps/pcbcalculator.png' },
    { 'KiCad PCB Editor (Standalone)', 'pcbnew', '/usr/share/icons/hicolor/128x128/apps/pcbnew.png' },
    { 'KiCad Schematic Editor (Standalone)', 'eeschema', '/usr/share/icons/hicolor/128x128/apps/eeschema.png' },
    { 'LibreOffice Math', 'libreoffice --math', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-math.png' },
    { 'XDot', 'xdot' },
}

appmenu.Engineering = {
    { 'FreeCAD', 'FreeCAD', '/usr/share/icons/hicolor/scalable/apps/org.freecadweb.FreeCAD.svg' },
    { 'LibreCAD', 'librecad', '/usr/share/icons/hicolor/128x128/apps/librecad.png' },
    { 'OpenSCAD', 'openscad', '/usr/share/pixmaps/openscad.png' },
    { 'PrusaSlicer', 'prusa-slicer', '/usr/share/icons/hicolor/128x128/apps/PrusaSlicer.png' },
}

appmenu.Games = {
    { 'Aseprite', 'steam steam://rungameid/431730', '/home/omegarogue/.local/share/icons/hicolor/16x16/apps/steam_icon_431730.png' },
    { 'Blender', 'steam steam://rungameid/365670', '/home/omegarogue/.local/share/icons/hicolor/16x16/apps/steam_icon_365670.png' },
    { 'DeSmuME (Gtk)', 'desmume', '/usr/share/icons/hicolor/scalable/apps/org.desmume.DeSmuME.svg' },
    { 'Factorio', 'steam steam://rungameid/427520', '/home/omegarogue/.local/share/icons/hicolor/16x16/apps/steam_icon_427520.png' },
    { 'Heroic Games Launcher', '/opt/Heroic/heroic', '/usr/share/icons/hicolor/128x128/apps/heroic.png' },
    { 'Starbound', 'steam steam://rungameid/211820', '/home/omegarogue/.local/share/icons/hicolor/16x16/apps/steam_icon_211820.png' },
    { 'Steam (Runtime)', '/usr/bin/steam-runtime', '/usr/share/pixmaps/steam.png' },
}

appmenu.Graphics = {
    { 'Document Scanner', 'simple-scan', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.SimpleScan.png' },
    { 'Document Viewer', 'evince', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.Evince.png' },
    { 'Flameshot', '/usr/bin/flameshot', '/usr/share/icons/hicolor/128x128/apps/org.flameshot.Flameshot.png' },
    { 'FontForge', 'fontforge', '/usr/share/icons/hicolor/128x128/apps/org.fontforge.FontForge.png' },
    { 'FreeCAD', 'FreeCAD', '/usr/share/icons/hicolor/scalable/apps/org.freecadweb.FreeCAD.svg' },
    { 'GNU Image Manipulation Program', 'gimp-2.10', '/usr/share/icons/hicolor/16x16/apps/gimp.png' },
    { 'Image Viewer', 'gpicview', '/usr/share/icons/hicolor/48x48/apps/gpicview.png' },
    { 'Inkscape', 'inkscape', '/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png' },
    { 'KGraphViewer', 'kgraphviewer -qwindowtitle "KGraphViewer"', '/usr/share/icons/hicolor/16x16/apps/kgraphviewer.png' },
    { 'Krita', 'krita', '/usr/share/icons/hicolor/128x128/apps/krita.png' },
    { 'LibreCAD', 'librecad', '/usr/share/icons/hicolor/128x128/apps/librecad.png' },
    { 'LibreOffice Draw', 'libreoffice --draw', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-draw.png' },
    { 'Okular', 'okular', '/usr/share/icons/hicolor/128x128/apps/okular.png' },
    { 'OpenSCAD', 'openscad', '/usr/share/pixmaps/openscad.png' },
    { 'Prusa GCode viewer', 'prusa-slicer --gcodeviewer', '/usr/share/icons/hicolor/128x128/apps/PrusaSlicer-gcodeviewer.png' },
    { 'PrusaSlicer', 'prusa-slicer', '/usr/share/icons/hicolor/128x128/apps/PrusaSlicer.png' },
    { 'Ristretto Image Viewer', 'ristretto', '/usr/share/icons/hicolor/128x128/apps/org.xfce.ristretto.png' },
    { 'XDot', 'xdot' },
    { 'XDvi', 'xdvi' },
}

appmenu.Internet = {
    { '', 'webview-permafrost --url http://localhost:3000/', '/home/omegarogue/.config/permafrost/icons/icon.png' },
    { 'AnyDesk', '/usr/bin/anydesk', '/usr/share/pixmaps/anydesk.svg' },
    { 'Avahi SSH Server Browser', '/usr/bin/bssh', '/usr/share/icons/Ambiant-MATE/status/22/network-wired.svg' },
    { 'Avahi VNC Server Browser', '/usr/bin/bvnc', '/usr/share/icons/Ambiant-MATE/status/22/network-wired.svg' },
    { 'Chromium', '/usr/bin/chromium', '/usr/share/icons/hicolor/128x128/apps/chromium.png' },
    { 'Discord', '/usr/bin/discord', '/usr/share/pixmaps/discord.png' },
    { 'Discord Canary', '/usr/bin/discord-canary', '/usr/share/pixmaps/discord-canary.png' },
    { 'Discord PTB', '/usr/bin/discord-ptb', '/usr/share/pixmaps/discord-ptb.png' },
    { 'DiscordQt', 'AppRun', '/usr/share/doc/cmake/html/_static/default.css' },
    { 'Electorrent', 'electorrent', '/usr/share/pixmaps/electorrent.png' },
    { 'Element', '/usr/bin/element-desktop', '/usr/share/icons/hicolor/128x128/apps/io.element.Element.png' },
    { 'FileZilla', 'filezilla', '/usr/share/pixmaps/filezilla.png' },
    { 'Firefox', '/usr/lib/firefox/firefox', '/usr/share/icons/hicolor/128x128/apps/firefox.png' },
    { 'Microsoft Edge', '/usr/bin/microsoft-edge-stable', '/usr/share/icons/hicolor/128x128/apps/microsoft-edge.png' },
    { 'Microsoft Teams - Preview', 'teams', '/usr/share/pixmaps/teams.png' },
    { 'Microsoft Teams for Linux', 'teams-for-linux', '/usr/share/icons/hicolor/128x128/apps/teams-for-linux.png' },
    { 'Permafrost', 'permafrost --gui', '/usr/share/pixmaps/permafrost.png' },
    { 'Signal', 'signal-desktop --', '/usr/share/icons/hicolor/128x128/apps/signal-desktop.png' },
    { 'SoftEther VPN Client Manager', 'vpncmgr /remote', '/usr/share/pixmaps/vpncmgr.png' },
    { 'SoftEther VPN Client Manager (Remote)', 'vpncmgr-remote', '/usr/share/pixmaps/vpncmgr.png' },
    { 'SoftEther VPN Server Manager', 'vpnsmgr', '/usr/share/pixmaps/vpnsmgr.png' },
    { 'Steam (Runtime)', '/usr/bin/steam-runtime', '/usr/share/pixmaps/steam.png' },
    { 'Teams', 'teams-nativefier', '/usr/share/icons/hicolor/128x128/apps/teams-nativefier.png' },
    { 'Telegram Desktop', 'telegram-desktop -quit', '/usr/share/icons/hicolor/128x128/apps/telegram.png' },
    { 'VNC Viewer', 'vncviewer', '/usr/share/icons/hicolor/48x48/apps/vncviewer48x48.png' },
    { 'WhatsApp', 'whatsapp-nativefier', '/usr/share/icons/hicolor/128x128/apps/whatsapp-nativefier.png' },
    { 'Zenmap', 'zenmap', '/usr/share/zenmap/pixmaps/zenmap.png' },
    { 'Zenmap (as root)', '/usr/share/zenmap/su-to-zenmap.sh', '/usr/share/zenmap/pixmaps/zenmap.png' },
    { 'local', 'webview-permafrost --url http://localhost:3000/ --chrome', '/home/omegarogue/.config/permafrost/icons/local/icon.png' },
}

appmenu.Office = {
    { 'Dictionary', 'xfce4-dict', '/usr/share/icons/hicolor/128x128/apps/org.xfce.Dictionary.png' },
    { 'Document Viewer', 'evince', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.Evince.png' },
    { 'Evolution', 'evolution', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/evolution.png' },
    { 'LibreOffice', 'libreoffice', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-startcenter.png' },
    { 'LibreOffice Base', 'libreoffice --base', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-base.png' },
    { 'LibreOffice Calc', 'libreoffice --calc', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-calc.png' },
    { 'LibreOffice Draw', 'libreoffice --draw', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-draw.png' },
    { 'LibreOffice Impress', 'libreoffice --impress', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-impress.png' },
    { 'LibreOffice Math', 'libreoffice --math', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-math.png' },
    { 'LibreOffice Writer', 'libreoffice --writer', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/libreoffice-writer.png' },
    { 'Okular', 'okular', '/usr/share/icons/hicolor/128x128/apps/okular.png' },
    { 'Zathura', 'zathura', '/usr/share/icons/hicolor/128x128/apps/org.pwmt.zathura.png' },
    { 'Zotero', '/usr/bin/zotero -url', '/usr/share/icons/hicolor/16x16/apps/zotero.png' },
}

appmenu.MultiMedia = {
    { 'Echomixer', 'echomixer', '/usr/share/icons/hicolor/48x48/apps/echomixer.png' },
    { 'Envy24 Control', 'envy24control', '/usr/share/icons/hicolor/48x48/apps/envy24control.png' },
    { 'HDAJackRetask', 'hdajackretask' },
    { 'HDSPConf', 'hdspconf', '/usr/share/icons/hicolor/48x48/apps/hdspconf.png' },
    { 'HDSPMixer', 'hdspmixer', '/usr/share/icons/hicolor/48x48/apps/hdspmixer.png' },
    { 'Helvum', 'helvum', '/usr/share/icons/hicolor/scalable/apps/org.pipewire.Helvum.svg' },
    { 'Hwmixvolume', 'hwmixvolume', '/usr/share/icons/hicolor/128x128/apps/hwmixvolume.png' },
    { 'LXMusic simple music player', 'lxmusic', '/usr/share/icons/hicolor/128x128/apps/lxmusic.png' },
    { 'NoiseTorch', 'noisetorch', '/usr/share/icons/hicolor/256x256/apps/noisetorch.png' },
    { 'Parole Media Player', 'parole --play', '/usr/share/icons/hicolor/128x128/apps/org.xfce.parole.png' },
    { 'PulseAudio Volume Control', 'pavucontrol', '/usr/share/icons/Yaru-MATE-dark/16x16/devices/multimedia-volume-control.png' },
    { 'PulseAudio Volume Meter (Capture)', 'pavumeter --record', '/usr/share/icons/gnome/24x24/devices/audio-input-microphone.png' },
    { 'PulseAudio Volume Meter (Playback)', 'pavumeter', '/usr/share/icons/gnome/24x24/devices/audio-input-microphone.png' },
    { 'Qt V4L2 test Utility', 'qv4l2', '/usr/share/icons/hicolor/16x16/apps/qv4l2.png' },
    { 'Qt V4L2 video capture utility', 'qvidcap', '/usr/share/icons/hicolor/16x16/apps/qvidcap.png' },
    { 'Spotify', 'spotify --uri=', '/usr/share/pixmaps/spotify-client.png' },
    { 'Xfburn', 'xfburn -i', '/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn.png' },
    { 'mpv Media Player', 'mpv --player-operation-mode=pseudo-gui --', '/usr/share/icons/hicolor/128x128/apps/mpv.png' },
    { 'qpwgraph', 'qpwgraph', '/usr/share/icons/hicolor/32x32/apps/org.rncbc.qpwgraph.png' },
}

appmenu.Settings = {
    { 'ARandR', 'arandr', '/usr/share/icons/gnome/16x16/devices/display.png' },
    { 'Advanced Network Configuration', 'nm-connection-editor', '/usr/share/icons/Ambiant-MATE/categories/24/preferences-system-network.svg' },
    { 'Bluetooth Manager', 'blueman-manager', '/usr/share/icons/hicolor/128x128/apps/blueman.png' },
    { 'Customize Look and Feel', 'lxappearance', '/usr/share/icons/Ambiant-MATE/apps/16/preferences-desktop-theme.svg' },
    { 'Desktop Preferences', 'pcmanfm --desktop-pref', '/usr/share/icons/Ambiant-MATE/places/128/user-desktop.svg' },
    { 'Grub Customizer', 'grub-customizer', '/usr/share/icons/hicolor/128x128/apps/grub-customizer.svg' },
    { 'Helvum', 'helvum', '/usr/share/icons/hicolor/scalable/apps/org.pipewire.Helvum.svg' },
    { 'Keyboard and Mouse', 'lxinput', '/usr/share/icons/Yaru-MATE-dark/16x16/devices/input-keyboard.png' },
    { 'Kvantum Manager', 'kvantummanager', '/usr/share/icons/hicolor/scalable/apps/kvantum.svg' },
    { 'Monitor Settings', 'lxrandr', '/usr/share/icons/Adwaita/512x512/devices/video-display.png' },
    { 'NVIDIA X Server Settings', '/usr/bin/nvidia-settings', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/nvidia-settings.png' },
    { 'Power Manager', 'xfce4-power-manager-settings', '/usr/share/icons/hicolor/128x128/apps/org.xfce.powermanager.png' },
    { 'Print Settings', 'system-config-printer', '/usr/share/icons/Yaru-MATE-dark/16x16/devices/printer.png' },
    { 'PulseAudio Volume Control', 'pavucontrol', '/usr/share/icons/Yaru-MATE-dark/16x16/devices/multimedia-volume-control.png' },
    { 'Qt5 Settings', 'qt5ct', '/usr/share/icons/Ambiant-MATE/apps/16/preferences-desktop-theme.svg' },
    { 'RazerGenie', 'razergenie', '/usr/share/icons/hicolor/scalable/apps/xyz.z3ntu.razergenie.svg' },
    { 'Setup Hot Keys', 'lxhotkey --gui=gtk', '/usr/share/icons/gnome/16x16/apps/preferences-desktop-keyboard.png' },
    { 'Text Editor Settings', 'mousepad --preferences', '/usr/share/icons/hicolor/128x128/apps/org.xfce.mousepad.png' },
    { 'Wacom Tablet finder', 'kde_wacom_tabletfinder', '/usr/share/icons/Adwaita/512x512/devices/input-tablet.png' },
    { 'spnavcfg', 'spnavcfg', '/usr/share/icons/hicolor/128x128/apps/spnavcfg.png' },
    { 'systemadm', 'systemadm', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/applications-system.png' },
    { 'wdisplays', 'wdisplays', '/usr/share/icons/hicolor/scalable/apps/network.cycles.wdisplays.svg' },
}

appmenu.System = {
    { 'Avahi Zeroconf Browser', '/usr/bin/avahi-discover', '/usr/share/icons/Ambiant-MATE/status/22/network-wired.svg' },
    { 'Btrfs Assistant', 'pkexec btrfs-assistant --xdg-desktop=$XDG_CURRENT_DESKTOP', '/usr/share/icons/hicolor/scalable/apps/btrfs-assistant.png' },
    { 'Dolphin', 'dolphin', '/usr/share/icons/Ambiant-MATE/apps/16/system-file-manager.svg' },
    { 'File Manager PCManFM', 'pcmanfm', '/usr/share/icons/Ambiant-MATE/apps/16/system-file-manager.svg' },
    { 'GParted', '/usr/bin/gparted', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/gparted.png' },
    { 'Grub Customizer', 'grub-customizer', '/usr/share/icons/hicolor/128x128/apps/grub-customizer.svg' },
    { 'Hardware Locality lstopo', 'lstopo', '/usr/share/hwloc/hwloc.dtd' },
    { 'Lens', 'open-lens', '/usr/share/icons/hicolor/512x512/apps/open-lens.png' },
    { 'Manage Printing', '/usr/bin/xdg-open http://localhost:631/', '/usr/share/icons/hicolor/128x128/apps/cups.png' },
    { 'Open Hardware Monitor', 'mono /opt/openhardwaremonitor/OpenHardwareMonitor.exe', '/opt/openhardwaremonitor/openhardwaremonitor.png' },
    { 'OpenJDK Java 18 Console', '/usr/lib/jvm/java-18-openjdk/bin/jconsole' },
    { 'OpenJDK Java 18 Shell', 'wezterm -e /usr/lib/jvm/java-18-openjdk/bin/jshell' },
    { 'Print Settings', 'system-config-printer', '/usr/share/icons/Yaru-MATE-dark/16x16/devices/printer.png' },
    { 'Razer Configuration', '/usr/bin/qrazercfg', '/usr/share/icons/hicolor/scalable/apps/razercfg.svg' },
    { 'Sensor Viewer', 'xfce4-sensors', '/usr/share/icons/hicolor/24x24/apps/xfce-sensors.png' },
    { 'SpaceFM', 'spacefm', '/usr/share/icons/hicolor/48x48/apps/spacefm.png' },
    { 'System Monitor', 'gnome-system-monitor', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/org.gnome.SystemMonitor.png' },
    { 'SystemdGenie', 'systemdgenie', '/usr/share/icons/Ambiant-MATE/categories/16/preferences-desktop.svg' },
    { 'Task Manager', 'lxtask', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/utilities-system-monitor.png' },
    { 'Task Manager', 'xfce4-taskmanager', '/usr/share/icons/hicolor/128x128/apps/org.xfce.taskmanager.png' },
    { 'UXTerm', 'uxterm', '/usr/share/pixmaps/xterm-color_48x48.xpm' },
    { 'Virtual Machine Manager', 'virt-manager', '/usr/share/icons/hicolor/16x16/apps/virt-manager.png' },
    { 'WezTerm', 'wezterm', '/usr/share/icons/hicolor/128x128/apps/org.wezfurlong.wezterm.png' },
    { 'XTerm', 'xterm', '/usr/share/pixmaps/xterm-color_48x48.xpm' },
    { 'dconf Editor', 'dconf-editor', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/ca.desrt.dconf-editor.png' },
    { 'lf', 'wezterm -e lf', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/utilities-terminal.png' },
    { 'nnn', 'wezterm -e nnn', '/usr/share/icons/hicolor/64x64/apps/nnn.png' },
    { 'ranger', 'wezterm -e ranger', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/utilities-terminal.png' },
    { 'systemadm', 'systemadm', '/usr/share/icons/Yaru-MATE-dark/16x16/apps/applications-system.png' },
}

appmenu.Miscellaneous = {
    { 'Anbox', 'anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity', '/usr/share/pixmaps/anbox.png' },
    { 'Autodesk Desktop App', 'env WINEPREFIX="/home/omegarogue/.wine" wine C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Start\\ Menu\\\\Programs\\\\Autodesk\\\\Autodesk\\ Desktop\\ App\\\\Autodesk\\ Desktop\\ App.lnk', '/home/omegarogue/.local/share/icons/hicolor/16x16/apps/D0F8_AutodeskDesktopApp.0.png' },
    { 'Calculator', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.calculator2 --component=com.android.calculator2.Calculator', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-calculator2.png' },
    { 'Calendar', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.calendar --component=com.android.calendar.AllInOneActivity', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-calendar.png' },
    { 'Clock', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.deskclock --component=com.android.deskclock.DeskClock', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-deskclock.png' },
    { 'Contacts', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.contacts --component=com.android.contacts.activities.PeopleActivity', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-contacts.png' },
    { 'Email', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.email --component=com.android.email.activity.Welcome', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-email.png' },
    { 'Fildem Hud', 'fildem-hud', '/usr/share/icons/Yaru-MATE-dark/16x16/legacy/search.svg' },
    { 'Files', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.documentsui --component=com.android.documentsui.LauncherActivity', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-documentsui.png' },
    { 'FluffyChat', '/opt/fluffychat/fluffychat', '/usr/share/pixmaps/fluffychat.png' },
    { 'Gallery', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.gallery3d --component=com.android.gallery3d.app.GalleryActivity', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-gallery3d.png' },
    { 'Goneovim', '/usr/bin/goneovim', '/usr/share/pixmaps/goneovim.ico' },
    { 'Google Play Store', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.vending --component=com.android.vending.AssetBrowserActivity', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-vending.png' },
    { 'Minitab', 'epiphany --application-mode "--profile=/home/omegarogue/.local/share/org.gnome.Epiphany.WebApp-minitab-3bd1a20479389ada88aeae62825dc98d2cb41cc5" https://app.minitab.com/', '/home/omegarogue/.local/share/org.gnome.Epiphany.WebApp-minitab-3bd1a20479389ada88aeae62825dc98d2cb41cc5/app-icon.png' },
    { 'Music', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.music --component=com.android.music.MusicBrowserActivity', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-music.png' },
    { 'OpenTabletDriver', '/usr/bin/otd-gui', '/usr/share/pixmaps/otd.png' },
    { 'Settings', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=com.android.settings --component=com.android.settings.Settings', '/home/omegarogue/.local/share/applications/anbox/anbox-com-android-settings.png' },
    { 'SuperSU', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=eu.chainfire.supersu --component=eu.chainfire.supersu.MainActivity-Material', '/home/omegarogue/.local/share/applications/anbox/anbox-eu-chainfire-supersu.png' },
    { 'WacomAreaX11 GUI', '/usr/bin/wacomareax11_gui' },
    { 'WebView Shell', '/usr/bin/anbox launch --action=android.intent.action.MAIN --package=org.chromium.webview_shell --component=org.chromium.webview_shell.WebViewBrowserActivity', '/home/omegarogue/.local/share/applications/anbox/anbox-org-chromium-webview_shell.png' },
}

appmenu.Appmenu = {
    { 'Accessories', appmenu.Accessories, '/usr/share/icons/gnome/16x16/categories/applications-utilities.png' },
    { 'Development', appmenu.Development, '/usr/share/icons/Yaru-MATE-dark/16x16/categories/applications-development.png' },
    { 'Education', appmenu.Education, '/usr/share/icons/breeze/categories/32/applications-education.svg' },
    { 'Science', appmenu.Science, '/usr/share/icons/gnome/16x16/categories/applications-science.png' },
    { 'Engineering', appmenu.Engineering, '/usr/share/icons/gnome/16x16/categories/applications-engineering.png' },
    { 'Games', appmenu.Games, '/usr/share/icons/Yaru-MATE-dark/16x16/categories/applications-games.png' },
    { 'Graphics', appmenu.Graphics, '/usr/share/icons/Ambiant-MATE/categories/16/applications-graphics.svg' },
    { 'Internet', appmenu.Internet, '/usr/share/icons/Ambiant-MATE/categories/16/applications-internet.svg' },
    { 'Office', appmenu.Office, '/usr/share/icons/Yaru-MATE-dark/16x16/apps/applications-office.png' },
    { 'MultiMedia', appmenu.MultiMedia, '/usr/share/icons/Ambiant-MATE/categories/24/applications-multimedia.svg' },
    { 'Settings', appmenu.Settings, '/usr/share/icons/Yaru-MATE-dark/16x16/categories/applications-accessories.png' },
    { 'System', appmenu.System, '/usr/share/icons/Yaru-MATE-dark/16x16/apps/applications-system.png' },
    { 'Miscellaneous', appmenu.Miscellaneous, '/usr/share/icons/Yaru-MATE-dark/16x16/categories/applications-other.png' },
}

return appmenu