 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Application Finder", "xfce4-appfinder", "/usr/share/icons/hicolor/16x16/apps/org.xfce.appfinder.png" },
     {"Archive Manager", "file-roller "},
     {"Barrier", "barrier"},
     {"Bitwarden", "bitwarden-desktop", "/usr/share/icons/hicolor/16x16/apps/bitwarden.png" },
     {"Bottles", "bottles "},
     {"Candle", "candle"},
     {"Characters", "/usr/bin/gnome-characters"},
     {"Disks", "gnome-disks"},
     {"Electorrent", "electorrent", "/usr/share/pixmaps/electorrent.png" },
     {"Files", "nautilus --new-window "},
     {"Flatseal", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.github.tchx84.Flatseal com.github.tchx84.Flatseal"},
     {"Fonts", "gnome-font-viewer "},
     {"HydraPaper", "/usr/bin/hydrapaper "},
     {"Image Viewer", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"Kvantum Manager", "kvantummanager"},
     {"Mousepad", "mousepad ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.mousepad.png" },
     {"Neovim", "xterm -e nvim ", "/usr/share/icons/hicolor/128x128/apps/nvim.png" },
     {"Nextcloud Desktop", "nextcloud ", "/usr/share/icons/hicolor/16x16/apps/Nextcloud.png" },
     {"NoiseTorch", "noisetorch", "/usr/share/icons/hicolor/256x256/apps/noisetorch.png" },
     {"Passwords and Keys", "seahorse "},
     {"Redshift", "redshift-gtk"},
     {"Screenkey", "screenkey", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-keyboard-shortcuts.png" },
     {"Screenshot", "xfce4-screenshooter", "/usr/share/icons/hicolor/16x16/apps/org.xfce.screenshooter.png" },
     {"Screenshot", "gnome-screenshot --interactive"},
     {"Uno Calculator", "uno-calculator", "/usr/share/icons/hicolor/16x16/apps/uno-calculator.png" },
     {"Vim", "xterm -e vim ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Wacom Settings", "wacom-settings"},
     {"Winetricks", "winetricks --gui"},
     {"XClicker", "xclicker", "/usr/share/icons/hicolor/256x256/apps/xclicker.png" },
     {"Xfburn", "xfburn"},
     {"YubiKey Personalization Tool", "yubikey-personalization-gui", "/usr/share/icons/hicolor/16x16/apps/yubikey-personalization-gui.png" },
     {"Yubico Authenticator", "yubioath-desktop", "/usr/share/pixmaps/com.yubico.yubioath.svg" },
     {"picom", "picom"},
     {"razerCommander", "/usr/bin/razercommander "},
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"FreeCAD", "FreeCAD "},
     {"GeoGebra", "geogebra"},
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"DeSmuME (Gtk)", "desmume"},
     {"Heroic Games Launcher", "/opt/heroic/heroic ", "/usr/share/pixmaps/heroic.png" },
     {"Lutris", "lutris ", "/usr/share/icons/hicolor/16x16/apps/lutris.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Thrive", "/opt/thrive/Thrive", "/usr/share/icons/Thrive.png" },
     {"higan", "higan", "/usr/share/pixmaps/higan.svg" },
     {"icarus", "icarus", "/usr/share/pixmaps/icarus.svg" },
     {"mGBA", "mgba-qt ", "/usr/share/pixmaps/mgba.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Document Scanner", "simple-scan"},
     {"Document Viewer", "evince "},
     {"Flameshot", "/usr/bin/flameshot", "/usr/share/icons/hicolor/48x48/apps/org.flameshot.Flameshot.png" },
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/org.fontforge.FontForge.png" },
     {"FreeCAD", "FreeCAD "},
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Image Viewer", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"ImageJ", "imagej ", "/usr/share/pixmaps/microscope.xpm" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png" },
     {"KGraphViewer", "kgraphviewer -qwindowtitle KGraphViewer ", "/usr/share/icons/hicolor/16x16/apps/kgraphviewer.png" },
     {"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/krita.png" },
     {"LibreCAD", "librecad ", "/usr/share/icons/hicolor/16x16/apps/librecad.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"OpenSCAD", "openscad ", "/usr/share/icons/hicolor/48x48/apps/openscad.png" },
     {"Peek", "peek"},
     {"Prusa GCode viewer", "prusa-slicer --gcodeviewer ", "/usr/share/icons/hicolor/32x32/apps/PrusaSlicer-gcodeviewer.png" },
     {"PrusaSlicer", "prusa-slicer ", "/usr/share/icons/hicolor/32x32/apps/PrusaSlicer.png" },
     {"Ristretto Image Viewer", "ristretto ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.ristretto.png" },
     {"Upscayl", "upscayl ", "/usr/share/pixmaps/upscayl.png" },
     {"XDot", "xdot "},
     {"XDvi", "xdvi "},
     {"ida", "ida ", "/usr/share/pixmaps/ida.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"AnyDesk", "/usr/bin/anydesk ", "/usr/share/pixmaps/anydesk.svg" },
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "/usr/bin/chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Discord", "/usr/bin/discord", "/usr/share/pixmaps/discord.png" },
     {"Discord Canary", "/usr/bin/discord-canary", "/usr/share/pixmaps/discord-canary.png" },
     {"Discord PTB", "/usr/bin/discord-ptb", "/usr/share/pixmaps/discord-ptb.png" },
     {"Electorrent", "electorrent", "/usr/share/pixmaps/electorrent.png" },
     {"Element", "/usr/bin/element-desktop ", "/usr/share/icons/hicolor/16x16/apps/io.element.Element.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Fluffychat", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=env --file-forwarding im.fluffychat.Fluffychat GDK_GL=gles fluffychat @@u  @@"},
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Microsoft Edge", "/usr/bin/microsoft-edge-stable ", "/usr/share/icons/hicolor/16x16/apps/microsoft-edge.png" },
     {"Microsoft Teams - Preview", "teams ", "/usr/share/pixmaps/teams.png" },
     {"Microsoft Teams for Linux", "teams-for-linux", "/usr/share/icons/hicolor/16x16/apps/teams-for-linux.png" },
     {"Permafrost", "permafrost --gui", "///usr/share/pixmaps/permafrost.png" },
     {"RustDesk", "rustdesk ", "/usr/share/icons/hicolor/256x256/apps/rustdesk.png" },
     {"Signal", "signal-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/signal-desktop.png" },
     {"SoftEther VPN Client Manager", "vpncmgr /remote", "/usr/share/pixmaps/vpncmgr.png" },
     {"SoftEther VPN Client Manager (Remote)", "vpncmgr-remote", "/usr/share/pixmaps/vpncmgr.png" },
     {"SoftEther VPN Server Manager", "vpnsmgr", "/usr/share/pixmaps/vpnsmgr.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Teams", "teams-nativefier", "/usr/share/icons/hicolor/16x16/apps/teams-nativefier.png" },
     {"Telegram Desktop", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=telegram-desktop --file-forwarding org.telegram.desktop -- @@u  @@", "/home/omegarogue/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/org.telegram.desktop.png" },
     {"WhatsApp", "whatsapp-nativefier", "/usr/share/icons/hicolor/16x16/apps/whatsapp-nativefier.png" },
     {"WhatsApp for Linux", "whatsapp-for-linux ", "/usr/share/icons/hicolor/16x16/apps/com.github.eneshecan.WhatsAppForLinux.png" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Dictionary", "xfce4-dict", "/usr/share/icons/hicolor/16x16/apps/org.xfce.Dictionary.png" },
     {"Document Viewer", "evince "},
     {"Evolution", "evolution "},
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Start Center", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Okular", "okular ", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Zathura", "zathura ", "/usr/share/icons/hicolor/16x16/apps/org.pwmt.zathura.png" },
     {"Zotero", "/usr/bin/zotero -url ", "/usr/share/icons/hicolor/16x16/apps/zotero.png" },
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"Goneovim", "/usr/bin/goneovim ", "///usr/share/pixmaps/goneovim.ico" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Arduino IDE", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=arduino --file-forwarding cc.arduino.arduinoide @@  @@", "/var/lib/flatpak/exports/share/icons/hicolor/16x16/apps/cc.arduino.arduinoide.png" },
     {"Arduino IDE", "\"/home/omegarogue/Downloads/arduino-1.8.19-linux64/arduino-1.8.19/arduino\"", "/usr/share/icons/hicolor/16x16/apps/arduino-arduinoide.png" },
     {"Arduino IDE", "arduino ", "/usr/share/icons/hicolor/16x16/apps/arduino.png" },
     {"CMake", "cmake-gui ", "/usr/local/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"D-Feet", "d-feet"},
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Electron 17", "electron17 ", "/usr/share/pixmaps/electron17.png" },
     {"Electron 19", "electron19 ", "/usr/share/pixmaps/electron19.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/32x32/apps/fluid.png" },
     {"PulseView", "pulseview", "/usr/share/icons/hicolor/48x48/apps/pulseview.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDBusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"RenderDoc", "qrenderdoc "},
     {"Segger JFlashExe", "/usr/bin/JFlashExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JFlashLiteExe", "/usr/bin/JFlashLiteExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JFlashSPIExe", "/usr/bin/JFlashSPIExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JFlashSPI_CL", "/usr/bin/JFlashSPI_CL", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkConfigExe", "/usr/bin/JLinkConfigExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkExe", "/usr/bin/JLinkExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkGDBServer", "/usr/bin/JLinkGDBServer", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkGUIServerExe", "/usr/bin/JLinkGUIServerExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkLicenseManager", "/usr/bin/JLinkLicenseManager", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkRTTClient", "/usr/bin/JLinkRTTClient", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkRTTLogger", "/usr/bin/JLinkRTTLogger", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkRTTViewer", "/usr/bin/JLinkRTTViewerExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkRegistration", "/usr/bin/JLinkRegistration", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkRemoteServer", "/usr/bin/JLinkRemoteServer", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkSTM32", "/usr/bin/JLinkSTM32", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JLinkSWOViewer", "/usr/bin/JLinkSWOViewer", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JMemExe", "/usr/bin/JMemExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JRunExe", "/usr/bin/JRunExe", "/usr/share/pixmaps/JLink.svg" },
     {"Segger JTAGLoadExe", "/usr/bin/JTAGLoadExe", "/usr/share/pixmaps/JLink.svg" },
     {"Unity Hub", "/opt/unityhub/unityhub ", "/usr/share/icons/hicolor/16x16/apps/unityhub.png" },
     {"UserFeedback Console", "UserFeedbackConsole", "/usr/share/icons/gnome/16x16/actions/search.png" },
     {"Visual Studio Code", "/usr/bin/code --unity-launch ", "/usr/share/icons/visual-studio-code.png" },
     {"bCNC", "python -m bCNC", "/usr/share/pixmaps/bcnc.png" },
     {"distcc monitor", "distccmon-gnome", "/usr/share/pixmaps/distccmon-gnome.png" },
     {"nRF Connect", "nrfconnect ", "/usr/share/icons/hicolor/16x16/apps/nrfconnect.png" },
     {"stlink", "stlink-gui"},
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"DSRemote", "dsremote", "/usr/share/icons/hicolor/48x48/apps/r_dsremote.png" },
     {"ImageJ", "imagej ", "/usr/share/pixmaps/microscope.xpm" },
     {"KiCad", "kicad ", "/usr/share/icons/hicolor/16x16/apps/kicad.png" },
     {"KiCad Gerber Viewer", "gerbview ", "/usr/share/icons/hicolor/16x16/apps/gerbview.png" },
     {"KiCad Image Converter", "bitmap2component ", "/usr/share/icons/hicolor/16x16/apps/bitmap2component.png" },
     {"KiCad PCB Calculator", "pcb_calculator", "/usr/share/icons/hicolor/16x16/apps/pcbcalculator.png" },
     {"KiCad PCB Editor (Standalone)", "pcbnew ", "/usr/share/icons/hicolor/16x16/apps/pcbnew.png" },
     {"KiCad Schematic Editor (Standalone)", "eeschema ", "/usr/share/icons/hicolor/16x16/apps/eeschema.png" },
     {"XDot", "xdot "},
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Cheese", "cheese"},
     {"Echomixer", "echomixer", "/usr/share/icons/hicolor/48x48/apps/echomixer.png" },
     {"Envy24 Control", "envy24control", "/usr/share/icons/hicolor/48x48/apps/envy24control.png" },
     {"HDAJackRetask", "hdajackretask"},
     {"HDSPConf", "hdspconf", "/usr/share/icons/hicolor/48x48/apps/hdspconf.png" },
     {"HDSPMixer", "hdspmixer", "/usr/share/icons/hicolor/48x48/apps/hdspmixer.png" },
     {"Helvum", "helvum"},
     {"Hwmixvolume", "hwmixvolume", "/usr/share/icons/hicolor/48x48/apps/hwmixvolume.png" },
     {"Kdenlive", "kdenlive ", "/usr/share/icons/hicolor/16x16/apps/kdenlive.png" },
     {"LXMusic simple music player", "lxmusic", "/usr/share/icons/hicolor/128x128/apps/lxmusic.png" },
     {"NoiseTorch", "noisetorch", "/usr/share/icons/hicolor/256x256/apps/noisetorch.png" },
     {"OBS Studio", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obs com.obsproject.Studio", "/var/lib/flatpak/exports/share/icons/hicolor/128x128/apps/com.obsproject.Studio.png" },
     {"OBS Studio", "obs", "/var/lib/flatpak/exports/share/icons/hicolor/128x128/apps/com.obsproject.Studio.png" },
     {"Parole Media Player", "parole ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.parole.png" },
     {"Peek", "peek"},
     {"PulseAudio Manager", "paman", "/usr/share/icons/gnome/16x16/devices/audio-card.png" },
     {"PulseAudio System Tray", "pasystray", "/usr/share/pixmaps/pasystray.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"PulseAudio Volume Meter (Capture)", "pavumeter --record", "///usr/share/icons/gnome/24x24/devices/audio-input-microphone.png" },
     {"PulseAudio Volume Meter (Playback)", "pavumeter", "///usr/share/icons/gnome/24x24/devices/audio-input-microphone.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"Spotify", "spotify --uri=", "/usr/share/pixmaps/spotify-client.png" },
     {"Syncplay", "syncplay ", "/usr/share/icons/hicolor/16x16/apps/syncplay.png" },
     {"Syncplay server", "xterm -e syncplay-server ", "/usr/share/icons/hicolor/16x16/apps/syncplay.png" },
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Xfburn", "xfburn"},
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"qpwgraph", "qpwgraph ", "/usr/share/icons/hicolor/32x32/apps/org.rncbc.qpwgraph.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"Alacritty", "alacritty", "/usr/share/pixmaps/Alacritty.svg" },
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Btrfs Assistant", "btrfs-assistant-launcher"},
     {"CPU-X", "cpu-x", "/usr/share/icons/hicolor/16x16/apps/cpu-x.png" },
     {"Color Profile Viewer", "gcm-viewer", "/usr/share/icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Dolphin", "dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Fedora Media Writer", "mediawriter", "/usr/share/icons/hicolor/16x16/apps/org.fedoraproject.MediaWriter.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Open Hardware Monitor", "mono /opt/openhardwaremonitor/OpenHardwareMonitor.exe ", "///opt/openhardwaremonitor/openhardwaremonitor.png" },
     {"OpenJDK Java 18 Console", "/usr/lib/jvm/java-18-openjdk/bin/jconsole"},
     {"OpenJDK Java 18 Shell", "xterm -e /usr/lib/jvm/java-18-openjdk/bin/jshell"},
     {"QDirStat", "qdirstat "},
     {"Razer Configuration", "/usr/bin/qrazercfg", "///usr/share/icons/hicolor/scalable/apps/razercfg.svg" },
     {"Sensor Viewer", "xfce4-sensors", "/usr/share/icons/hicolor/24x24/apps/xfce-sensors.png" },
     {"System Monitor", "gnome-system-monitor"},
     {"SystemdGenie", "systemdgenie", "/usr/share/icons/gnome/16x16/categories/preferences-desktop.png" },
     {"Task Manager", "xfce4-taskmanager", "/usr/share/icons/hicolor/16x16/apps/org.xfce.taskmanager.png" },
     {"Terminal", "gnome-terminal"},
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Virtual Machine Manager", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
     {"WezTerm", "wezterm start --cwd . --", "/usr/share/icons/hicolor/128x128/apps/org.wezfurlong.wezterm.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"btop++", "xterm -e btop", "/usr/share/icons/hicolor/48x48/apps/btop.png" },
     {"dconf Editor", "dconf-editor"},
     {"kitty", "kitty", "/usr/share/icons/hicolor/256x256/apps/kitty.png" },
     {"lf", "xterm -e lf", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"nnn", "xterm -e nnn", "/usr/share/icons/hicolor/64x64/apps/nnn.png" },
     {"ranger", "xterm -e ranger", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

xdgmenu = {
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}

