---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by omegarogue.
--- DateTime: 06.06.22 16:42
---

local _M = {}

-- This is used later as the default Terminal and Editor to run.
_M.terminal = "wezterm"
_M.editor = os.getenv("EDITOR") or "nvim"
_M.editor_cmd = _M.terminal .. " -e " .. _M.editor

-- Default Modkey.
_M.modkey = "Mod4"

_M.raise_volume_cmd = "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 +5%"
_M.lower_volume_cmd = "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 -5%"
_M.set_volume_cmd = "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 $v%"
_M.volume_mute_cmd = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
_M.run_prompt_cmd = "rofi -show run"
_M.power_menu_cmd = "rofi -show power-menu"
_M.screenshot_cmd = "flameshot gui"
_M.video_screenshot_cmd = "peek"

return _M
