#!/bin/sh
# from https://github.com/BrodieRobertson/scripts/blob/master/dragon/cpdragon
files=$(dragon-drag-and-drop -t -x)

for file in $files
do
  path=${file#file://}
  name=$(basename "$path")
  cp "$path" "$(pwd)/$name"
done
