export MAGIC_ENTER_OTHER_COMMAND='ls -lha .'

export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"


export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$HOME/.dotnet:/usr/local/go/bin:/home/omegarogue/.local/bin:/mnt/d/Programs/mupdf-1.18.0-windows:~/.npm-global/bin:~/go/bin

export MANPAGER="nvim -c MANPAGER -"
export PAGER="nvim -c PAGER -"

export GPG_TTY=$(tty)

export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
