#setopt SOURCE_TRACE

if [[ $(uname -r) == *WSL* ]]; then
	$HOME/.local/bin/gpg-agent-relay start
fi

setopt autocd
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

source $HOME/.zsh_plugins

function magic-enter-cmd {
	if command git rev-parse --is-inside-work-tree &>/dev/null; then
		echo ' git status -u .'
	else
		echo ' [[ $(ls . |wc -l) -le 30 ]] && ls -lh . || ls .'
	fi
}

#powerline-daemon -q
#. '/home/omegarogue/.local/lib/python3.8/site-packages/powerline/bindings/zsh/powerline.zsh'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.zsh_aliases ]; then
  . ~/.zsh_aliases
fi

# ensure correct PATH zshenv
source $HOME/.zshenv


if [[ -z $SSH_CONNECTION ]]; then
	gpgconf --launch gpg-agent
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


fpath+=${ZDOTDIR:-~}/.zsh_functions

autoload -U +X bashcompinit && bashcompinit
#eval $(opam env)
complete -o nospace -C /usr/bin/nomad nomad

. $HOME/.local/lib/python3.10/site-packages/powerline/bindings/zsh/powerline.zsh

