$HOME/.local/bin/gpg-agent-relay start

source ~/.dotfiles/antigen/antigen.zsh
antigen init ~/.antigenrc






# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.zsh_aliases ]; then
  . ~/.zsh_aliases
fi

# ensure correct PATH zshenv
source $HOME/.zshenv




[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
